### ISSUE TITLE
Data structure from mobile

### ISSUE THREAD

**Issue by Bart63** [PercentEquals/LocStats#18]

**Comment by guszczi** [comment]
Example of multiple gps data transfer
```json
[
  {
    "timestamp": 1,
    "latitude": 2,
    "longitude": 3
  },
  {
    "timestamp": 4,
    "latitude": 5,
    "longitude": 6
  }
]
```

**Comment by Bart63** [comment]
I prepared in 69e036690055e321460fbd0d513035d381e5de9b `OnReachedSize()` method with `IEnumerable<LocationModel> bufferLocations` variable.
You can call your method to create a request from there, @slimak7
