### ISSUE TITLE
Draw data as lines on map when showing data from previous dates

### ISSUE THREAD

**Issue by PercentEquals** [PercentEquals/LocStats#39]

**Comment by Bart63** [comment]
Now we have available creating polylines and markers if we want
![image](https://user-images.githubusercontent.com/30702198/140843859-bb76433a-866c-446e-8be4-2c04c9318e5a.png)
Polyline can have some styling later.

**Comment by Bart63** [comment]
Effect after last commit 
![image](https://user-images.githubusercontent.com/30702198/143627296-6d5e222c-92e1-4d03-8fc7-3e67640625d5.png)
